### ISSUE TITLE
Improve sample table component

### ISSUE THREAD

**Issue by ml-evs** [datalab-org/datalab#254]
We can use a prebaked table component that allows client-side filtering.

Desired features (please edit and expand):

- [x] All existing features of "old" sample table
- [ ] Pagination
    - [x] Client-side for now, but eventually server side too
- [x] Client-side search (free-text)
- [ ] Client-side filtering, e.g., categorical columns
- [x] Sortable columns
- [ ] Selectable/hideable columns client-side
- [x] Collapsible rows with more info
- [x] Selectable rows with actions available, e.g., delete, or add to collection
- [ ] Support for sorting/filtering derived data types like datetime
- [ ] Dynamic columns based on the API responses

**Comment by ml-evs** [comment]
Related to admin dashboard (#576); might need a better table component for that too. Unfortunately https://www.npmjs.com/package/vue3-easy-data-table is no longer actively developed so might need to look elsewhere (cc @BenjaminCharmes)

**Comment by jdbocarsly** [comment]
The good news is there are more options that work nicely with vue 3 now:

https://tabulator.info/examples/5.6
https://www.ag-grid.com/
https://ui.vuestic.dev/ui-elements/data-table
https://primevue.org/datatable/
https://quasar.dev/vue-components/table/

**Comment by ml-evs** [comment]
Feel free to assign yourself @BenjaminCharmes if you start having a look at this (or let me know if you don't have permission to assign yourself)

**Comment by ml-evs** [comment]
Also extend the thought in this issue to paginating the API response, now that some users have 100+ entries

**Comment by ml-evs** [comment]
@BenjaminCharmes could you summarise briefly the ones you tried out and which ones work? I will add a feature checklist to the top comment that maybe @jdbocarsly can look at and add to aswell.

**Comment by ml-evs** [comment]
Potentially one more to have a look at: https://github.com/carbon-design-system/carbon-components-vue

We could consider adopting an overall design system if we find one we like, but for now we can just take inspiration from their tables

**Comment by ml-evs** [comment]
potentially related issue: https://github.com/ag-grid/ag-grid/issues/7274

**Comment by BenjaminCharmes** [comment]
As I said last week, Ag Grid seems a bit tricky for rendering custom components inside cells, even if it does work.

So I started again with Primevue, and it seems to be even easier. Here's what it looks like at the moment (everything is customizable):

![Screenshot 2024-07-03 at 14 52 12](https://github.com/the-grey-group/datalab/assets/107116804/2ad30563-10f3-41d9-9535-cc07fe999edc)

**Comment by ml-evs** [comment]
Looks great! It seems that primevue does have all the features we discussed above too. Could you try enabling filtering for creators or sample type just to see how it works? e.g. https://primevue.org/datatable/#filter

**Comment by BenjaminCharmes** [comment]
Yes, I'd done it. You can put a "global" search bar and/or a search bar on one (or several) specific columns.
It works pretty well, except for Creators at the moment, I'll have to take a closer look at why.

<img width="1210" alt="Screenshot 2024-07-05 at 15 41 41" src="https://github.com/the-grey-group/datalab/assets/107116804/c1577f93-551a-405f-8e3c-0c46b8f633d8">
