### ISSUE TITLE
Cannot remove entries from the Equipments tab

### ISSUE THREAD

**Issue by KusalvinD** [datalab-org/datalab#835]

**Comment by ml-evs** [comment]
I think this currently requires admin priveleges, but we could set it up in the same way as starting materials with an option corresponding to `VUE_EDITABLE_STARTING_MATERIALS` for instruments.

**Comment by ml-evs** [comment]
This is closed by #1020, but not entirely in a satisfactory way; users can now create/edit/delete starting materials and equipment as they please, regardless of who made them. Probably I will tweak it so that they at least cannot delete this kind of data, but they can update it.
