### ISSUE TITLE
Unable to upload files to items in Inventory

### ISSUE THREAD

**Issue by KusalvinD** [datalab-org/datalab#880]
Uploading still works for items in "Samples", but fails in uploading to items in Inventory and Equipment. 

![Screenshot 2024-09-18 115613](https://github.com/user-attachments/assets/097df40e-5a05-49f0-9c46-7f4c5bdd99ba)
![Screenshot 2024-09-18 115835](https://github.com/user-attachments/assets/e1c49c6d-a4cf-4a25-a1b1-2ac240585f53)

**Comment by ml-evs** [comment]
Hi @KusalvinD, thanks for reporting. I think this is a consequence of the migration of the Bocarsly group to new hardware. Previously we applied a patch that allowed any user to upload files to inventory items, and we essentially need to make this possible for everyone again. I'll prepare the patch as a PR to this repo and we can deploy on your system to test it.

**Comment by KusalvinD** [comment]
Great, Thanks!

**Comment by PeterKraus** [comment]
We ran into this issue this week, too. The admin user can still upload files, but the user that created the object cannot.
